### ISSUE TITLE
Typos in README.md

### ISSUE THREAD

**Issue by Jelinek-J** [mittinatten/freesasa#60]
```
git submodules init
git supmodules update
```
should probably be
```
git submodule init
git submodule update
```
i.e. 'b' instead of 'p' in the second one and remove 's' in both.
And as submodules are completely new for me, shouldn't be more secure to add `--recursive` to them too?

P.S.: Checks for 'libc++-11-dev' and 'libc++abi-11-dev' maybe should be added to configure script (at least in WSL2 Ubuntu 20.04 they are missing by default).

**Comment by mittinatten** [comment]
Hi,
Thanks for the feedback. I will fix the typo immediately.

Since we are locked to a specific version of Gemmi where everything works without recursive submodules, we should be fine without `--recursive` for now.

I'll see what I can do about the missing dependency checks, to make sure it doesn't break on other platforms. Nothing special seems to be necessary on Mac OS or regular Ubuntu 16.

**Comment by mittinatten** [comment]
Hi again,
The Readme was fixed a while back. I don't have access to WSL. I thought `AX_CXX_COMPILE_STDCXX([14])` in `configure.ac` should take care of any C++ deps. If you're still having trouble with this, can you add whatever is needed to solve the situation in WSL to `configure.ac` and submit a PR? Then I will verify that it doesn't break anything else. I will close this issue since that is separate from the readme typos.
